version: '3'
services:
   db:
     image: mariadb:10.5-focal
     restart: always
     environment:
       MYSQL_DATABASE: $MYSQL_DATABASE
       MYSQL_USER: $MYSQL_USER
       MYSQL_PASSWORD: $MYSQL_PASSWORD
       MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "$WORDPRES_EXTERNAL_PORT:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
       WORDPRESS_DB_USER: $WORDPRESS_DB_USER
       WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
     volumes:
      - ./wordpress/wp-content/themes/twentytwentyfour/:/var/www/html/wp-content/themes/twentytwentyfour